### ISSUE TITLE
Hyprsome works fine via command-line, but fails when used as a keybinding

### ISSUE THREAD

**Issue by cwillsey06** [sopa0/hyprsome#2]
If I run `hyprsome workspace 2` in a terminal, the workspace switches, as expected.  
However, using the same command in a Hyprland keybinding does nothing at all.

Here's my relevant hyprland.conf keybindings  
```
# Workspaces
bind = $Strong, 1, exec, hyprsome workspace 1
bind = $Strong, 2, exec, hyprsome workspace 2
bind = $Strong, 3, exec, hyprsome workspace 3
bind = $Strong, 4, exec, hyprsome workspace 4
bind = $Strong, 5, exec, hyprsome workspace 5
bind = $Strong, 6, exec, hyprsome workspace 6
bind = $Strong, 7, exec, hyprsome workspace 7
bind = $Strong, 8, exec, hyprsome workspace 8
bind = $Strong, 9, exec, hyprsome workspace 9

# Move window to a workspace
bind = $Strong SHIFT, 1, exec, hyprsome move 1
bind = $Strong SHIFT, 2, exec, hyprsome move 2
bind = $Strong SHIFT, 3, exec, hyprsome move 3
bind = $Strong SHIFT, 4, exec, hyprsome move 4
bind = $Strong SHIFT, 5, exec, hyprsome move 5
bind = $Strong SHIFT, 6, exec, hyprsome move 6
bind = $Strong SHIFT, 7, exec, hyprsome move 7
bind = $Strong SHIFT, 8, exec, hyprsome move 8
bind = $Strong SHIFT, 9, exec, hyprsome move 9
```  

Something interesting of note, when I login to a tty, and use the command `dbus-launch Hyprland`, the keybindings do work as expected, with no issues at all. I tried adding said command to my hyprland.desktop file, but it unfortunately didn't work.   

I use SDDM as a display manager, [`sugar-light`](https://github.com/MarianArlt/sddm-sugar-light) as my theme.  
Fedora Workstation 37

**Comment by cwillsey06** [comment]
I forgot to include my workspace bindings.  
```
# Bind workspaces (hyprsome)
# Primary (DP-2)
monitor = DP-2, preferred, 0x0, 1
workspace = DP-2, 11

wsbind = 11, DP-2
wsbind = 12, DP-2
wsbind = 13, DP-2
wsbind = 14, DP-2
wsbind = 15, DP-2
wsbind = 16, DP-2
wsbind = 17, DP-2
wsbind = 18, DP-2
wsbind = 19, DP-2

# Secondary (DP-1)
monitor = DP-1, preferred, 1920x0, 1
workspace = DP-1, 1

wsbind = 1, DP-1
wsbind = 2, DP-1
wsbind = 3, DP-1
wsbind = 4, DP-1
wsbind = 5, DP-1
wsbind = 6, DP-1
wsbind = 7, DP-1
wsbind = 8, DP-1
wsbind = 9, DP-1
```  
...and the output of `hyprctl monitors`  
```
$ hyprctl monitors
Monitor DP-1 (ID 0):
	1920x1080@74.973000 at 1920x0
	description: Acer Technologies SB220Q 0x0000F7CD (DP-1 via HDMI)
	active workspace: 1 (1)
	reserved: 0 26 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1

Monitor DP-2 (ID 1):
	1920x1080@60.000000 at 0x0
	description: Acer Technologies SB220Q 0x0000FACC (DP-2 via HDMI)
	active workspace: 11 (11)
	reserved: 0 26 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
```

**Comment by erikdubois** [comment]
tried it to today
was unsuccesfull

can you share your .dot files for hyprland so we can analyze a working system

**Comment by cwillsey06** [comment]
Yes, the repo's here https://github.com/cwillsey06/hyprdots

**Comment by erikdubois** [comment]
thanks - will check it out

**Comment by sopa0** [comment]
yeah I'm aware of that issue, a guy from Hyprland Discord had the same, never managed to reproduce it

**Comment by iErik** [comment]
Could it be that Hyprland just can't find the hyprsome executable? I'm using fish shell for example, cargo is set to in the PATH variable but idk if that could be causing some issue with Hyprland

**Comment by iErik** [comment]
I just tried running `hyprctl dispatch exec hyprsome workspace 1` here and it didn't work, `hyprctl dispatch exec ~/.cargo/bin/hyprsome workspace 1` worked fine tho, that must be the issue.

**Comment by cwillsey06** [comment]
> I just tried running `hyprctl dispatch exec hyprsome workspace 1` here and it didn't work, `hyprctl dispatch exec ~/.cargo/bin/hyprsome workspace 1` worked fine tho, that must be the issue.

Seems to have worked! I'll close this now. Thank you.
