### ISSUE TITLE
hyprsome taking me to the wrong workspace

### ISSUE THREAD

**Issue by w34o** [sopa0/hyprsome#20]
Hi i just installed hyprsome and added this to my config:

workspace=1,monitor:DP-1
workspace=2,monitor:DP-1
workspace=3,monitor:DP-1
workspace=4,monitor:DP-1
workspace=5,monitor:DP-1

workspace=6,monitor:HDMI-A-1
workspace=7,monitor:HDMI-A-1
workspace=8,monitor:HDMI-A-1
workspace=9,monitor:HDMI-A-1
workspace=10,monitor:HDMI-A-1

bind = $SUPER, 1, exec, hyprsome workspace 1
bind = $SUPER, 2, exec, hyprsome workspace 2
bind = $SUPER, 3, exec, hyprsome workspace 3
bind = $SUPER, 4, exec, hyprsome workspace 4
bind = $SUPER, 5, exec, hyprsome workspace 5
bind = $SUPER, 6, exec, hyprsome workspace 6
bind = $SUPER, 7, exec, hyprsome workspace 7
bind = $SUPER, 8, exec, hyprsome workspace 8
bind = $SUPER, 9, exec, hyprsome workspace 9
bind = $SUPER, 0, exec, hyprsome workspace 10

When I save the file and press $SUPER+# it takes me to that workspace +10. For example pressing $SUPER+1 takes me to workspace 11 and $SUPER+0 takes me to 110(??). The only way I can get back workspace 1 is by opening a window and $mainMod+shift+1'ing it back to the first workspace.

**Comment by w34o** [comment]
fixed 
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

**Comment by Aadniz** [comment]
The bigger question is, why can't it be 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 instead of 11, 12, 13, 14, 15, 16, 17, 18, 19, 110 ?
